name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: volume-solide.tex
          working_directory: exercices
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: volume-solide.pdf
          path: exercices/volume-solide.pdf
